Features/http api
icosa-gallery/open-brush pull request #155
Opened 2021-08-08 09:42 UTC by andybak

OK. This is a big one.

2021-08-08 09:50 UTC, mikeage commented
It looks like you didn't have the `pre-commit` hook installed for (some of?) these commits; can you run it once manually with `pre-commit run -a`?

2021-08-08 10:00 UTC, mikeage reviewed
A few questions, mostly for my understanding.

2021-08-08 10:25 UTC, andybak commented on Assets/Scripts/SketchControlsScript.cs
> +                    // TODO refactor code above to use this method
Maybe - but there's a sense in which the API is always going to be a work in progress. A small refactor like this is quite far down my list. If that's a release blocker then it's going to be a decade before I can do a PR.

2021-08-08 10:26 UTC, andybak commented on Assets/Scripts/SketchControlsScript.cs
> +                    //m_SketchSurface.SetActive(!m_ViewOnly);
It's low impact and I think it's an improvement. But more eyeballs might inform a better decision.

2021-08-08 10:27 UTC, andybak commented on Assets/Scripts/Sharing/HttpServer.cs
> +                        if (App.UserConfig.Flags.EnableApiCorsHeaders)
The only place they are currently documented is in the "Tilt Brush Release Notes" - I agree they probably should be moved in to the main docs. But oh. We don't have any!

2021-08-08 10:28 UTC, mikeskydev commented on Assets/Scripts/Sharing/HttpServer.cs
> +                        if (App.UserConfig.Flags.EnableApiCorsHeaders)
I cloned the release notes onto our group google drive, but I agree it really needs transposed somewhere more open!

2021-08-08 10:31 UTC, mikeage commented on Assets/Scripts/SketchControlsScript.cs
> +                    // TODO refactor code above to use this method
sure, I just wanted to check :-)

2021-08-08 10:35 UTC, andybak commented on Assets/Scripts/Sharing/HttpServer.cs
> +                        if (App.UserConfig.Flags.EnableApiCorsHeaders)
Yeah. I'll update that. That doc is linked to from https://docs.google.com/document/d/1gjoYp4y-1qlE3a7fvXVxGR3ioj3nMfgprmTHQ-bpq0k/edit which to my mind is the primary entry point to docs. I'll update it to point to your copy and add my settings there.

At some point we can fold the release notes into the main doc.

2021-09-22 04:00 UTC, mikeage commented
You seem to be using this a lot... any reason not to merge it?

2021-09-22 08:33 UTC, andybak commented
I'm on the fence. I don't think it's the end of the world if we merge this and end up changing some of the command naming later on. I also think the fundamental approach is ok (key/value pairs, agnostic to transport and syntax) and I'm happy to defend those design decisions.

However I'm still on the fence about the synchronous vs asynchronous question so I guess I'm wondering whether changing our minds on this would have knock-on effects.

On the other hand - nobody is using it much at the moment and it's not discoverable unless we signpost it in the docs. So we can make sure the docs clearly state it's experimental and subject to change. It's always going to be niche so we're unlikely to create much ire with future breaking changes.

The only other thing I'd like some eyeballs on is security. Currently it's opt-in for anything other than local connections. But I'm not sure if this is easy to spoof? And when you do opt-in to connections from other machines on the network - we're exposing stuff that's never been poked at from a security perspective (file loading/saving, import/export).

Luckily accepting WAN connections require some effort on the part of the user (localtunnel, port forwarding etc).

Assuming spoofing isn't an issue, maybe just a big "Don't turn on non-localhost unless you're on a trusted network" warning would be enough.

2021-09-22 09:51 UTC, mikeage commented
Gotcha. I agree about WAN connections. I think my main question was if you're waiting for time or anything else... it seems like while you're not completely sure about everything, waiting isn't really going to improve it, as no one is actively thinking about it. I'd propose merging it, maybe one or two of the other big PRs (monoscopic, Moat, etc) and then start thinking about 0.5; we know that very few users actually take pre-release versions, so the only real way to get feedback is with a formal release

2021-09-22 10:05 UTC, andybak commented
Yeah but I can't see what will ever get the API out of limbo. I want feedback from others and it ain't happening at the moment. That's what I mean by "on the fence" - I'm tempted to recommend merging this as well as I can't see another route to getting more eyes on it. Security issues are the only thing that gives me pause. If you think what I've said above is solid enough for a merge then maybe it's fine.

2021-09-22 10:09 UTC, mikeage commented
I'm fine with it. Let's see what other cool stuff the community can come up with, and what, if any, changes they'd like

2021-11-12 08:42 UTC, mikeage commented on Assets/Scenes/Main.unity
> +  Secrets: {fileID: 11400000, guid: 94ce910a09cb4944f9100b4be96da57f, type: 2}
What was this change about? From the commit, I thought it might have been undoing something in the branch, but I see it's still present.

2021-11-15 04:18 UTC, mikeage requested changes

2021-11-15 04:18 UTC, mikeage commented on Assets/Scenes/Main.unity
> +  Secrets: {fileID: 11400000, guid: 94ce910a09cb4944f9100b4be96da57f, type: 2}
Please revert before merge

2021-11-16 13:00 UTC, mikeage approved these changes
LGTM, works, but I can't comment on code quality. Coder quality is good, though ;-)

2021-11-16 21:26 UTC, mikeskydev commented
nit: Can all new scripts be added to the `TiltBrush` namespace and have the licence at the top of the files?

2021-11-18 12:36 UTC, mikeage commented
It looks like there are a few conflicts now

2021-12-05 19:26 UTC, mikeskydev commented
Merged via #200

2021-12-05 19:26 UTC, closed without merging