Features/moatmerge plus pr198
icosa-gallery/open-brush pull request #200
Opened 2021-11-27 15:42 UTC by andybak

2021-12-03 23:52 UTC, mikeskydev requested changes

2021-12-03 23:52 UTC, mikeskydev commented on Assets/Editor/BrushTagger.cs
> +﻿using System.Collections.Generic;
You know what I'm going to say :)

2021-12-05 14:31 UTC, mikeage approved these changes
Seems to work for me. So all I can do is link to https://twitter.com/iamdevloper/status/397664295875805184

2021-12-05 19:16 UTC, mikeskydev approved these changes

2021-12-05 19:23 UTC, merged