Unity minor version and package update
icosa-gallery/open-brush pull request #203
Opened 2021-12-06 16:16 UTC by andybak

This is probably a good time to bump the latest 2019.4 and update a few packages.

2021-12-06 16:34 UTC, mikeage requested changes
Please update the GitHub Actions yaml as well

2021-12-06 16:39 UTC, mikeskydev commented
Should anything related to quicksearch be committed? there's also a UserSettings folder that might need to be gitignored

2021-12-06 17:07 UTC, andybak commented
> Should anything related to quicksearch be committed? there's also a UserSettings folder that might need to be gitignored

They just seem to be config files. You're right about UserSettings though. I've removed that file gitignored the directory.

2021-12-06 18:03 UTC, andybak commented
Can anyone see what's wrong with the build? It's the licence file but the commit looks fine:

https://github.com/IxxyXR/open-brush/commit/4061e88a9041dd37a6cf9f907704100d2918a35d

I'll retry the build just in case it was a remote error.

2021-12-06 18:08 UTC, mikeage commented
OK, I know what's wrong. I'm on my mobile now, will write more later. We need to update the license (fallback) to match the unity version.

2021-12-07 04:07 UTC, mikeage requested changes

2021-12-07 04:07 UTC, mikeage commented on .github/workflows/build.yml
> +  UNITY_LICENSE: ${{ fromJSON('["<?xml version=\"1.0\" encoding=\"UTF-8\"?><root>\n    <License id=\"Terms\">\n        <MachineBindings>\n            <Binding Key=\"1\" Value=\"576562626572264761624c
The license was generated with 2019.4.25f1, so we need to keep that part. It's still valid for 2019.4.33f1 though (in earlier PRs, I'd updated the license with each unity version update, but it turns out that this shouldn't be necessary.)

In other words, revert this change, and just leave line 14. 

(confirmation: https://discord.com/channels/710946343828455455/710946344264794219/917566961054007308, from the game-ci discord server)

2021-12-07 14:13 UTC, mikeage commented on .github/workflows/build.yml
>            wget -q https://download.packages.unity.com/com.unity.textmeshpro/-/com.unity.textmeshpro-2.1.4.tgz -O tmp.plugin/plugin.tgz
can you update this line please? :-)

2022-03-22 09:27 UTC, andybak commented
Let's forget this - the 2020 update is on the horizon.

2022-03-22 09:27 UTC, closed without merging