Feature/remove geometry intersection shader
icosa-gallery/open-brush pull request #475
Opened 2023-07-20 15:36 UTC by andybak

This removes all the clever stuff and does something mind-boggling simple instead. I will be very surprised if this fix works.

2023-07-30 16:13 UTC, andybak commented
Note for testing - if you want to simulate running on a Quest 1 (and therefore use the new code path) set GeometryShaderSuppported to always return false.

Last time I tested, there was a major crash loading some scenes when using this code path.

2023-08-03 09:37 UTC, mikeskydev requested changes
Works on Quest 1. Nice stuff! Just a few nits.

2023-08-03 09:37 UTC, mikeskydev commented on Assets/Resources/Brushes/Shared/Shaders/Special/Intersection.shader
> -
No need for this!

2023-08-03 09:37 UTC, mikeskydev commented on Assets/Resources/Brushes/Shared/Shaders/Special/IntersectionNonGeomFallback.shader
> +// Copyright 2020 The Tilt Brush Authors
Year, attribution change

2023-08-03 13:37 UTC, merged